### ISSUE TITLE
stylesheet helper not wotking

### ISSUE THREAD

**Issue by leite** [endel/slim-lightncandy-view#1]
Hi.

nice lib, I'm trying to use it but I got an error using the following view ...

``` handlebars
<html>

  <head>
    <title>Foo</title>
    {{ stylesheet 'css/bootstrap.css' }}
  </head>

  <body>
    <div class='main'>
```

php error ...

``` bash
PHP Fatal error:  Class 'Request' not found in /tmp/lci_JC6ynN on line 15
```

**Comment by endel** [comment]
Hey @leite, thanks for reporting this! 

This library was made tied to another codebase, it was not entirely decoupled. Now it's ok!
