### ISSUE TITLE
block_helpers settings key wrong

### ISSUE THREAD

**Issue by kenesa** [endel/slim-lightncandy-view#7]
There is an issue with the key used to see if there is any block_helpers defined in the $settings array in the __construct() method. 

```
        $this->block_helpers = $this->getBlockHelpers();
        if (isset($settings['helpers'])) {
            $this->block_helpers = array_merge($this->block_helpers, $settings['block_helpers']);
        }
```
It should be `if (isset($settings['block_helpers']))`.

**Comment by endel** [comment]
Hi @kenesa. Could you send me a pull-request fixing that? Thanks.

**Comment by endel** [comment]
I've just pushed a fix for this @kenesa. Thanks for reporting.
