### ISSUE TITLE
Class missing \ArrayAccess

### ISSUE THREAD

**Issue by kenesa** [endel/slim-lightncandy-view#8]
The class Lightncandy has the methods needed to implement the `\ArrayAccess`, `\IteratorAggregate` and `\Countable` interfaces, but these interfaces are not referenced when the class is declared. This causes an `Error` when the object is referenced as an array with PHP 7.0 (sorry, I don't have PHP 5.x loaded anywhere to test with).

**Comment by endel** [comment]
Can you paste the stack trace here?

It seems something related to Lightncandy library itself. 

Cheers

**Comment by kenesa** [comment]
Here you go.

Fatal error: Uncaught Error: Cannot use object of type Slim\Views\Lightncandy as array
Error: Cannot use object of type Slim\Views\Lightncandy as array
```
<?php
require_once('../vendor/autoload.php');
$view = new \Slim\Views\Lightncandy('templates');
$view['Title'] = 'Testing ArrayAccess';
```
The Error goes away when I changed the declaration of the class to:

```
class Lightncandy implements \Pimple\ServiceProviderInterface, \ArrayAccess, \IteratorAggregate, \Countable
{
```

**Comment by kenesa** [comment]
Opps. Hit the wrong button and I can't seem to unclose the comment.

**Comment by kenesa** [comment]
Here you go.

Fatal error: Uncaught Error: Cannot use object of type Slim\Views\Lightncandy as array
Error: Cannot use object of type Slim\Views\Lightncandy as array
```
<?php
require_once('../vendor/autoload.php');
$view = new \Slim\Views\Lightncandy('templates');
$view['Title'] = 'Testing ArrayAccess';
```
The Error goes away when I changed the declaration of the class to:

```
class Lightncandy implements \Pimple\ServiceProviderInterface, \ArrayAccess, \IteratorAggregate, \Countable
{
```

**Comment by endel** [comment]
@kenesa You're not supposed to change the view's data like this. 

Please take a look at the usage example: https://github.com/endel/slim-lightncandy-view/blob/master/example/index.php

You should use the `render` method to pass data to the template.

**Comment by kenesa** [comment]
Perhaps the quick example I provided to reproduce the error is causing some confusion. The only reason that I would use the ArrayAccess interface to populate `$defaultVariables` would be for configuration values that need to be passed to the template. When processing a specific request, I would use the `$data` argument of the `fetch()` method for all request specific information.

Can you please explain what you intended the `$defaultVariables` to be used for?

**Comment by endel** [comment]
You're totally right. Sorry, I haven't touched this project in a while, now I see your point. I've just updated the class with your fix. Thanks!

**Comment by kenesa** [comment]
Thank you!
